const cart       = require('./modules/cart')
const collect    = require('./modules/collect')
const home       = require('./modules/home')
const login      = require('./modules/login')
const member     = require('./modules/member')
const merchant   = require('./modules/merchant')
const order      = require('./modules/order')
const product    = require('./modules/product')
const chbook     = require('./modules/chbook')
const rebook     = require('./modules/rebook')
const register   = require('./modules/register')
const service    = require('./modules/service')
const wishlist   = require('./modules/wishlist')
const classes      = require('./modules/classes')

// const { authenticated } = require('../middleware/auth')

module.exports = app => {
  app.use('/cart', cart)
  app.use('/collect', collect)
  app.use('/home', home)
  app.use('/login', login)
  app.use('/member', member)
  app.use('/merchant', merchant)
  app.use('/order', order)
  app.use('/product', product)
  app.use('/chbook', chbook)
  app.use('/rebook', rebook)
  app.use('/register', register)
  app.use('/service', service)
  app.use('/wishlist', wishlist)
  app.use('/classification', classes )
  app.use('/', (req, res) => { return res.redirect('/home') })
}
