const cart       = require('../route/modules/cart')
const collect    = require('../route/modules/collect')
const home       = require('../route/modules/home')
const login      = require('../route/modules/login')
const member     = require('../route/modules/member')
const merchant   = require('../route/modules/merchant')
const order      = require('../route/modules/order')
const product    = require('../route/modules/product')
const rebook     = require('../route/modules/rebook')
const register   = require('../route/modules/register')
const service    = require('../route/modules/service')
const wishlist   = require('../route/modules/wishlist')

// const { authenticated } = require('../middleware/auth')

module.exports = app => {
  app.use('/cart', cart)
  app.use('/collect', collect)
  app.use('/home', home)
  app.use('/login', login)
  app.use('/member', member)
  app.use('/merchant', merchant)
  app.use('/order', order)
  app.use('/product', product)
  app.use('/rebook', rebook)
  app.use('/register', register)
  app.use('/service', service)
  app.use('/wishlist', wishlist)
  app.use('/', (req, res) => { return res.redirect('/home') })
}
